import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SocialNetworks, Navbar } from "@/components";

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative bg-black text-white ${poppins.className}`}>
        <Navbar />
        {children}
        <SocialNetworks />
      </body>
    </html>
  );
}
